"use strict";
const suppliers=["Spizarnia","Mastermedia","Wabar"];
const key="mieszko-ordering-ui-v1";
const sample={products:[{code:"12345",description:"Sample dairy 500g",barcodes:["5901234567890","5901234567891"]},{code:"23456",description:"Sample biscuits 250g",barcodes:["5901234567005"]}],mappings:[{code:"12345",supplier:"Spizarnia",supplierCode:"SP-1005"},{code:"12345",supplier:"Mastermedia",supplierCode:"MM-7821"},{code:"12345",supplier:"Wabar",supplierCode:"WB-4450"},{code:"23456",supplier:"Spizarnia",supplierCode:"SP-1006"},{code:"23456",supplier:"Wabar",supplierCode:"WB-4451"}],prices:[{supplier:"Spizarnia",supplierCode:"SP-1005",casePrice:16.2,caseSize:12},{supplier:"Mastermedia",supplierCode:"MM-7821",casePrice:14.64,caseSize:12},{supplier:"Wabar",supplierCode:"WB-4450",casePrice:15.48,caseSize:12},{supplier:"Spizarnia",supplierCode:"SP-1006",casePrice:8,caseSize:10},{supplier:"Wabar",supplierCode:"WB-4451",casePrice:7.5,caseSize:10}],requirements:[],drafts:[]};
let state;try{state=JSON.parse(localStorage.getItem(key))||structuredClone(sample)}catch{state=structuredClone(sample)}
const el=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),money=n=>"£"+Number(n).toFixed(2);
function persist(){localStorage.setItem(key,JSON.stringify(state));render()}
function toast(s){el("toast").textContent=s;el("toast").style.display="block";setTimeout(()=>el("toast").style.display="none",3600)}
function product(code){return state.products.find(p=>p.code===code)}
function mapped(supplier,supplierCode){return state.mappings.find(m=>m.supplier===supplier&&m.supplierCode===supplierCode)}
function priceOptions(code){return state.prices.flatMap(p=>{const m=mapped(p.supplier,p.supplierCode);return m&&m.code===code&&p.caseSize>0&&p.casePrice>=0?[{...p,code,unitPrice:p.casePrice/p.caseSize}]:[]})}
function selectTab(tab){document.querySelectorAll("main section").forEach(s=>s.classList.toggle("hidden",s.id!==tab));document.querySelectorAll("aside button").forEach(b=>b.classList.toggle("active",b.dataset.tab===tab));el("heading").textContent=({dashboard:"Ordering Dashboard",products:"Product Mapping",prices:"Supplier Prices",planning:"Order Planning",orders:"Draft Orders"})[tab];}
document.querySelectorAll("aside button").forEach(b=>b.onclick=()=>selectTab(b.dataset.tab));
for(const id of ["mapSupplier","priceSupplier"])el(id).innerHTML=suppliers.map(s=>'<option>'+esc(s)+'</option>').join("");
function render(){
el("metrics").innerHTML=[["Products",state.products.length],["Supplier mappings",state.mappings.length],["Approved prices",state.prices.length],["Draft lines",state.drafts.length]].map(([n,v])=>'<div class="card"><div class="muted">'+n+'</div><div class="metric">'+v+'</div></div>').join("");
el("summary").innerHTML='<table><thead><tr><th>Supplier</th><th>Mapped products</th><th>Approved prices</th></tr></thead><tbody>'+suppliers.map(s=>'<tr><td>'+s+'</td><td>'+state.mappings.filter(m=>m.supplier===s).length+'</td><td>'+state.prices.filter(p=>p.supplier===s).length+'</td></tr>').join("")+'</tbody></table>';
el("mappingRows").innerHTML=state.mappings.map(m=>{const p=product(m.code);return '<tr><td>'+esc(m.code)+'</td><td>'+esc(p?.description)+'</td><td>'+esc(p?.barcodes.join(", "))+'</td><td>'+esc(m.supplier)+'</td><td>'+esc(m.supplierCode)+'</td></tr>'}).join("");
el("priceRows").innerHTML=state.prices.map(p=>{const m=mapped(p.supplier,p.supplierCode);return '<tr><td>'+esc(p.supplier)+'</td><td>'+esc(p.supplierCode)+'</td><td>'+esc(m?.code||"Unmapped")+'</td><td>'+p.caseSize+'</td><td>'+money(p.casePrice)+'</td><td>'+money(p.casePrice/p.caseSize)+'</td></tr>'}).join("");
el("planProduct").innerHTML=state.products.map(p=>'<option value="'+esc(p.code)+'">'+esc(p.code+" — "+p.description)+'</option>').join("");
el("requirementRows").innerHTML=state.requirements.map((r,i)=>'<tr><td>'+esc(r.store)+'</td><td>'+esc(r.code)+'</td><td>'+esc(product(r.code)?.description)+'</td><td>'+r.units+'</td><td><button class="secondary" data-remove="'+i+'">Remove</button></td></tr>').join("");
document.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{state.requirements.splice(Number(b.dataset.remove),1);persist()});
el("orderContent").innerHTML=state.drafts.length?suppliers.map(s=>{const rows=state.drafts.filter(d=>d.supplier===s);if(!rows.length)return "";return '<h3>'+esc(s)+'</h3><div class="wide"><table><thead><tr><th>Store</th><th>MSP Code</th><th>Supplier code</th><th>Cases</th><th>Units</th><th>Net total</th></tr></thead><tbody>'+rows.map(d=>'<tr><td>'+esc(d.store)+'</td><td>'+esc(d.code)+'</td><td>'+esc(d.supplierCode)+'</td><td>'+d.cases+'</td><td>'+d.units+'</td><td>'+money(d.total)+'</td></tr>').join("")+'</tbody></table></div><p><strong>Subtotal: '+money(rows.reduce((a,d)=>a+d.total,0))+'</strong></p>'}).join(""):'<p>No drafts generated yet.</p>';
}
el("mappingForm").onsubmit=e=>{e.preventDefault();const code=el("msp").value.trim(),description=el("desc").value.trim(),supplier=el("mapSupplier").value,supplierCode=el("supplierCode").value.trim(),barcodes=el("barcodes").value.split(",").map(s=>s.trim()).filter(Boolean);if(!code||!supplierCode||!description)return;const conflict=state.mappings.find(m=>m.supplier===supplier&&m.supplierCode===supplierCode&&m.code!==code);if(conflict)return toast("Supplier code is already mapped to another MSP item.");for(const b of barcodes){if(state.products.some(p=>p.code!==code&&p.barcodes.includes(b)))return toast("Barcode "+b+" is already linked to another MSP product.")}let p=product(code);if(!p){p={code,description,barcodes:[]};state.products.push(p)}p.description=description;p.barcodes=[...new Set([...p.barcodes,...barcodes])];if(!state.mappings.some(m=>m.code===code&&m.supplier===supplier&&m.supplierCode===supplierCode))state.mappings.push({code,supplier,supplierCode});persist();e.target.reset();toast("Product mapping saved in browser.")};
function parseCsv(text){const rows=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'&&quoted&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')quoted=!quoted;else if(c===","&&!quoted){row.push(cell);cell=""}else if((c==="\n"||c==="\r")&&!quoted){if(c==="\r"&&text[i+1]==="\n")i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell=""}else cell+=c}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);if(quoted)throw Error("Invalid CSV quotes");return rows}
let pending=[];
el("uploadPrices").onclick=async()=>{const file=el("priceFile").files[0];if(!file)return toast("Choose a CSV file.");try{const rows=parseCsv(await file.text());const header=rows.shift().map(s=>s.trim().toLowerCase().replace(/^\uFEFF/,""));const indices=["supplier_code","net_case_price","units_per_case"].map(n=>header.indexOf(n));if(indices.includes(-1))throw Error("Required CSV columns: supplier_code,net_case_price,units_per_case");const supplier=el("priceSupplier").value;pending=rows.map((r,i)=>{const [code,price,size]=indices.map(j=>(r[j]||"").trim());const mapping=mapped(supplier,code);if(!mapping)throw Error("Row "+(i+2)+": unmapped supplier code "+code);if(!price||!size||!Number.isFinite(Number(price))||!Number.isFinite(Number(size))||Number(price)<0||Number(size)<=0)throw Error("Row "+(i+2)+": invalid price or case size");return {supplier,supplierCode:code,casePrice:Number(price),caseSize:Number(size)}});if(!pending.length)throw Error("No prices found");el("preview").innerHTML='<p class="good">'+pending.length+' mapped prices ready for approval.</p><button class="primary" id="approvePrices">Approve and apply prices</button>';el("approvePrices").onclick=()=>{for(const p of pending){state.prices=state.prices.filter(x=>!(x.supplier===p.supplier&&x.supplierCode===p.supplierCode));state.prices.push(p)}pending=[];el("preview").innerHTML="";persist();toast("Prices approved and saved locally.")}}catch(e){pending=[];el("preview").textContent="";toast(e.message)}};
el("addRequirement").onclick=()=>{const store=el("storeName").value.trim(),code=el("planProduct").value,units=Number(el("requiredUnits").value);if(!store||!Number.isSafeInteger(units)||units<=0)return toast("Enter store and a positive whole-unit quantity.");const r=state.requirements.find(x=>x.store===store&&x.code===code);if(r)r.units+=units;else state.requirements.push({store,code,units});persist();toast("Requirement added.")};
el("generate").onclick=()=>{const drafts=[],errors=[];for(const r of state.requirements){const options=priceOptions(r.code).map(o=>({...o,cases:Math.ceil(r.units/o.caseSize),total:Math.ceil(r.units/o.caseSize)*o.casePrice})).sort((a,b)=>a.total-b.total||a.unitPrice-b.unitPrice||a.supplier.localeCompare(b.supplier));if(!options.length){errors.push(r.code+" has no mapped approved price");continue}const o=options[0];drafts.push({store:r.store,code:r.code,supplier:o.supplier,supplierCode:o.supplierCode,cases:o.cases,units:o.cases*o.caseSize,total:o.total})}if(errors.length)return toast("Draft not generated: "+errors.join("; "));state.drafts=drafts;persist();selectTab("orders");toast("Drafts generated. Review before ordering.")};
el("exportOrders").onclick=()=>{if(!state.drafts.length)return toast("No drafts to export.");const cols=["store","supplier","code","supplierCode","cases","units","total"];const quote=s=>'"'+String(s).replace(/"/g,'""')+'"';const csv=[cols.join(","),...state.drafts.map(r=>cols.map(c=>quote(r[c])).join(","))].join("\r\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));const a=document.createElement("a");a.href=url;a.download="mieszko-draft-orders.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
el("clearDrafts").onclick=()=>{if(confirm("Clear all draft orders?")){state.drafts=[];persist()}};
render();