import { describe, expect, it } from "vitest";
import { extractText } from "unpdf";
import type { EmailOrder } from "@/lib/order-message";
import { orderPdfFilename } from "@/lib/order-message";
import { renderOrderPdf } from "@/server/pdf/render-order-pdf";

function orderWith(lines: EmailOrder["lines"], overrides: Partial<EmailOrder> = {}): EmailOrder {
  return {
    id: "9f0c0a6e-2b5d-4c1a-9a11-perivale",
    orderNumber: "MO-TEST-001",
    storeId: "store-perivale",
    storeName: "Perivale",
    storeCode: "0766",
    storeEmail: "perivale@example.com",
    supplierName: "Polish Village Bread",
    supplierEmail: "orders@bread.example",
    supplierCc: [],
    orderDate: "2026-09-29",
    deliveryDate: "2026-10-08",
    lines,
    ...overrides,
  };
}

async function readPdf(order: EmailOrder) {
  const buffer = await renderOrderPdf(order);
  const extracted = await extractText(new Uint8Array(buffer), { mergePages: false });
  const pages = extracted.text as string[];
  return { buffer, pages, totalPages: extracted.totalPages, text: pages.join("\n") };
}

describe("order PDF", () => {
  it("contains the shop, supplier, delivery date and ordered products", async () => {
    const order = orderWith([
      { itemCode: "1029", ean: "590111", supplierCode: "PVB-1", name: "100% RYE YEAST FREE BREAD", polishName: "CHLEB 100% ŻYTNI BEZ DROŻDŻY", quantity: 6 },
      { itemCode: "0000", ean: "000", supplierCode: "ZERO", name: "ZERO BREAD", polishName: null, quantity: 0 },
      { itemCode: "1044", ean: "590222", supplierCode: "PVB-2", name: "Rye with cranberry", polishName: "Bułeczki drożdżowe", quantity: 2 },
    ]);
    const pdf = await readPdf(order);

    expect(orderPdfFilename(order)).toBe("Mieszko-Order-0766-Polish-Village-Bread-08-10-2026.pdf");
    expect(pdf.buffer.subarray(0, 4).toString()).toBe("%PDF");
    expect(pdf.text).toContain("Perivale");
    expect(pdf.text).toContain("0766");
    expect(pdf.text).toContain("Polish Village Bread");
    expect(pdf.text).toContain("08/10/2026");
    expect(pdf.text).toContain("29/09/2026");
    expect(pdf.text).toContain("100% RYE YEAST FREE BREAD");
    expect(pdf.text).toContain("CHLEB 100% ŻYTNI BEZ DROŻDŻY");
    expect(pdf.text).toContain("Bułeczki drożdżowe");
    expect(pdf.text).toContain("Rye with cranberry");
    expect(pdf.text).not.toContain("ZERO BREAD");
    expect(pdf.text).toContain("Total Products: 2");
    expect(pdf.text).toContain("Total Qty: 8");
    expect(pdf.text).toContain("Generated by Mieszko Office Operations");
  });

  it("creates a valid multi-page PDF for a long order and repeats the table header", async () => {
    const lines = Array.from({ length: 80 }, (_, index) => ({
      itemCode: `ITEM-${index + 1}`,
      ean: `590000${index}`,
      supplierCode: `SUP-${index + 1}`,
      name: `Product ${index + 1}`,
      polishName: index === 79 ? "Ostatni chleb żytni" : null,
      quantity: index + 1,
    }));
    const pdf = await readPdf(orderWith(lines));

    expect(pdf.totalPages).toBeGreaterThan(1);
    expect(pdf.pages[0]).toContain("Product 1");
    expect(pdf.pages[0]).toContain("ITEM CODE");
    expect(pdf.pages.at(-1)).toContain("Product 80");
    expect(pdf.pages.at(-1)).toContain("ITEM CODE");
    expect(pdf.pages.at(-1)).toContain("Ostatni chleb żytni");
    expect(pdf.text).toContain("Total Products: 80");
  });
});
